apiVersion: v1
kind: Pod
metadata:
  name: test-backend-image
spec:
  containers:
  - name: backend
    image: todo-backend:minikube
    command: ['python', '-c', 'import uvicorn; print("uvicorn available"); import sys; print(sys.version)']
  restartPolicy: Never