{{- if .Values.secrets.create }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secrets.name }}
  labels:
    {{- include "todo-app.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- with .Values.secrets.databaseUrl }}
  {{ .key }}: "" # Set this value manually or use --set-file
  {{- end }}
  {{- with .Values.secrets.openaiApiKey }}
  {{ .key }}: "" # Set this value manually or use --set-file
  {{- end }}
  {{- with .Values.secrets.jwtSecret }}
  {{ .key }}: "" # Set this value manually or use --set-file
  {{- end }}
  {{- with .Values.secrets.betterAuthSecret }}
  {{ .key }}: "" # Set this value manually or use --set-file
  {{- end }}
{{- end }}
